version: '3.1'

services:
  db:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
    - 5601:5601
  logstash:
    build: ./logstash
    ports:
      - 5044:5044
      - 9600:9600
